apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kmx-edc-ui.fullname" . }}-secret
  labels:
    {{- include "kmx-edc-ui.labels" . | nindent 4 }}
type: Opaque
data:
  edc-api-key: {{ .Values.edc.apiKey | b64enc | quote }}
  {{- if not .Values.postgresql.enabled }}
  {{- if not .Values.externalDatabase.existingSecret }}
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- end }}
